name: "FlightBot"

on: 
  pull_request:
    types: [opened, edited, review_requested, ready_for_review]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Label PR and Issues
    steps:
      - name: Checkout # Only needed for development use
        uses: actions/checkout@v2
      - name: Label pull request and related issues
        uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          review-trigger: "please review"
          merge-label: "5: Ready for merge"
          review-label: "6: PR for review"
