name: "FlightBot"

on: 
  pull_request:
    types: [opened, edited, review_requested]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Label PR and Issues
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Label pull request and related issues
        uses: ./ # Uses an action in the root directory
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          review-trigger: "please review"
          merge-label: "5: Ready for merge"
          review-label: "6: PR for review"
